language: node_js
node_js:
    - "8"
    - "10"
    - "11"
    - "12"
before_install:
    - npm config set scripts-prepend-node-path true
    - yarn cache clean
install:
    - yarn --no-lockfile
before_script:
    - yarn lerna bootstrap
script:
    - yarn lint
    - yarn test
