language: node_js
node_js:
    - "8"
    - "10"
    - "11"
    - "12"
before_install:
    - yarn cache clean
install:
    - yarn install --ignore-engines
script:
    - yarn lint
    - yarn test
before_deploy:
  - yarn docs
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on: # deploy only tagged build on Node.js 10
        tags: true
        node: '10'
