language: node_js
node_js:
  - "8"
  - "10"
  - "11"
script:
  - npm run test
deploy:
  provider: pages
  script: npm run docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on: # deploy only tagged build on Node.js 10
    tags: true
    node: '10'
