language: node_js
node_js:
  - "8"
  - "10"
  - "11"
branches:
    except:
    - v0.6.0
script:
  - npm run test
before_deploy:
  - npm run docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on: # deploy only tagged build on Node.js 10
    tags: true
    node: '10'
